# Inherit properties from defaults
function(baker_inherit_defaults target)
    set(defaults_list ${ARGN})
    target_link_libraries(${target} INTERFACE ${defaults_list})
    foreach(default IN LISTS defaults_list)
        if(NOT TARGET ${default})
            message(WARNING "Target '${default}' does not exist. Skipping inherit_defaults.")
            # WARN: too much missing defaults, add dummy target here
            add_library(${default} INTERFACE)
        else()
            get_property(keys TARGET ${default} PROPERTY _ALL_KEYS_)
            foreach(key IN LISTS keys)
                get_property(value TARGET ${default} PROPERTY ${key})
                set_property(TARGET ${target} APPEND PROPERTY ${key} ${value})
            endforeach()
        endif()
    endforeach()
endfunction()

# Apply defaults to a target with proper include directories and libraries
function(baker_apply_defaults target)
    set(defaults_list ${ARGN})
    target_link_libraries(${target} PRIVATE ${defaults_list})
    foreach(default IN LISTS defaults_list)
        baker_apply_properties(${target} ${default})
    endforeach()
endfunction()
