function(baker_transform_source_file target SCOPE SOURCE_FILE)
    get_filename_component(file_name ${SOURCE_FILE} NAME_WE)
    get_filename_component(file_ext ${SOURCE_FILE} EXT)
    if(file_name MATCHES "\\*")
        file(GLOB_RECURSE file_list ${SOURCE_FILE})
        set(SOURCE_FILE ${file_list})
    elseif(file_name MATCHES "^:")
        # Convert ":file_name" to target link "file_name"
        string(SUBSTRING ${file_name} 1 -1 dependency)
        set(SOURCE_FILE "")
        target_link_libraries(${target} ${SCOPE} ${dependency})
    endif()
    set(SOURCE_FILE "${SOURCE_FILE}" PARENT_SCOPE)
endfunction(baker_transform_source_file)

function(baker_apply_sources_transform target)
    get_target_property(private_sources ${target} SOURCES)
    if(private_sources STREQUAL "private_sources-NOTFOUND")
        set(private_sources "")
    endif()

    get_target_property(interface_sources ${target} INTERFACE_SOURCES)
    if(interface_sources STREQUAL "interface_sources-NOTFOUND")
        set(interface_sources "")
    endif()

    set(new_private_sources "")
    # Loop through all sources
    foreach(SOURCE_FILE ${private_sources})
        baker_transform_source_file(${target} PRIVATE ${SOURCE_FILE})
        list(APPEND new_private_sources ${SOURCE_FILE})
    endforeach()
    set(new_interface_sources "")
    foreach(SOURCE_FILE ${interface_sources})
        baker_transform_source_file(${target} INTERFACE ${SOURCE_FILE})
        list(APPEND new_interface_sources ${SOURCE_FILE})
    endforeach()

    set_property(TARGET ${target} PROPERTY SOURCES ${new_private_sources})
    set_property(TARGET ${target} PROPERTY INTERFACE_SOURCES ${new_interface_sources})
endfunction(baker_apply_sources_transform)