function(transform_source target SCOPE SOURCE_FILE)
    get_filename_component(file_name ${SOURCE_FILE} NAME_WE)
    get_filename_component(file_ext ${SOURCE_FILE} EXT)
    if (file_name MATCHES "\\*")
        file(GLOB_RECURSE file_list ${SOURCE_FILE})
        set(SOURCE_FILE "")
        target_sources(${target} ${SCOPE} ${file_list})
    elseif (file_name MATCHES "^:")
        string(SUBSTRING ${file_name} 1 -1 VARIABLE_NAME)
        set(SOURCE_FILE "")
        target_sources(${target} ${SCOPE} $<TARGET_PROPERTY:${VARIABLE_NAME},INTERFACE_SOURCES>)
    elseif(file_ext STREQUAL ".yy")
        find_package(BISON)
        get_filename_component(file_path ${SOURCE_FILE} ABSOLUTE)
        # Run bison_target on the .yy file
        bison_target(${FILE_NAME}_parser ${file_path} "${CMAKE_CURRENT_BINARY_DIR}/${file_name}.cpp" DEFINES_FILE ${CMAKE_CURRENT_BINARY_DIR}/${file_name}.h)
        set(SOURCE_FILE ${BISON_${FILE_NAME}_parser_OUTPUTS})
        target_include_directories(${target} ${SCOPE} ${CMAKE_CURRENT_BINARY_DIR})
    elseif(file_ext STREQUAL ".ll")
        find_package(FLEX)
        get_filename_component(FILE_PATH ${SOURCE_FILE} ABSOLUTE)
        # Run flex_target on the .ll file
        flex_target(${file_name}_lexer ${FILE_PATH} "${CMAKE_CURRENT_BINARY_DIR}/${file_name}.cpp")
        set(SOURCE_FILE ${FLEX_${file_name}_lexer_OUTPUTS})
        target_include_directories(${target} ${SCOPE} ${CMAKE_CURRENT_BINARY_DIR})
    endif()
    set(SOURCE_FILE "${SOURCE_FILE}" PARENT_SCOPE)
endfunction(transform_source)

function(apply_sources_transform target)
    get_target_property(private_sources ${target} SOURCES)
    if(private_sources STREQUAL "private_sources-NOTFOUND")
        set(private_sources "")
    endif()

    get_target_property(interface_sources ${target} INTERFACE_SOURCES)
    if(interface_sources STREQUAL "interface_sources-NOTFOUND")
        set(interface_sources "")
    endif()

    set(new_private_sources "")
    # Loop through all sources
    foreach(SOURCE_FILE ${private_sources})
        transform_source(${target} PRIVATE ${SOURCE_FILE})
        list(APPEND new_private_sources ${SOURCE_FILE})
    endforeach()
    set(new_interface_sources "")
    foreach(SOURCE_FILE ${interface_sources})
        transform_source(${target} PUBLIC ${SOURCE_FILE})
        list(APPEND new_interface_sources ${SOURCE_FILE})
    endforeach()

    set_property(TARGET ${target} PROPERTY SOURCES ${new_private_sources})
    set_property(TARGET ${target} PROPERTY INTERFACE_SOURCES ${new_interface_sources})
endfunction(apply_sources_transform)