name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  makefile-build:
    uses: ./.github/workflows/build-test-reusable.yml
    with:
      build_name: "Makefile"
      cmake_generator: "Unix Makefiles"

  ninja-build:
    uses: ./.github/workflows/build-test-reusable.yml
    with:
      build_name: "Ninja"
      cmake_generator: "Ninja"
